### ISSUE TITLE
Python 2.7 error on import

### ISSUE THREAD

**Issue by arrase** [meganz/sdk#435]
Taked from example code:

```
>>> import mega
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mega
```

Ok , let's see:

```
# ls /usr/local/lib/python2.7/dist-packages/
libmega
```

let's try again:

```
>>> import libmega
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/libmega/__init__.py", line 2, in <module>
    from mega import *
  File "/usr/local/lib/python2.7/dist-packages/libmega/mega.py", line 28, in <module>
    _mega = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/libmega/mega.py", line 24, in swig_import_helper
    _mod = imp.load_module('_mega', fp, pathname, description)
ImportError: libmega.so.600: cannot open shared object file: No such file or directory
>>> 
```

But is in default path:

```
 # find / -name libmega.so.600
 /usr/local/lib/libmega.so.600
 ^C
```

Oupss!!

I am doing something wrong?

**Comment by polmr** [comment]
Did you follow the instructions at https://github.com/meganz/sdk/tree/master/bindings/python to install mega bindings? It should place a "mega" (not libmega) package at ~/.local/lib/python2.7/site-packages .
