### ISSUE TITLE
Segmentation fault on logout using Python bindings 

### ISSUE THREAD

**Issue by acappiello** [meganz/sdk#69]
A recent commit appears to have broken logging out in the Python bindings. Prior to updating today, I was on commit bea10a7c819ce0d915e2777a81050b1bab3bbbd3 and this did not happen. I have reproduced this with Python 2.7.6 and 3.4.0 on Linux Mint 17.1 and with Python 2.6.6 on CentOS 6.6.

Steps to reproduce:
```
$ cd examples/python
$ gdb python
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
(gdb) r megacli.py 
Starting program: /usr/bin/python megacli.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffee084700 (LWP 30970)]
Mega sample app. Type help or ? to list commands.

(MEGA) login EMAIL PASSWORD
INFO: Request start ( LOGIN )
(MEGA) (MEGA) INFO: Request finished ( LOGIN )   Result: No error
(MEGA) INFO: Request start ( FETCH_NODES )
(MEGA) INFO: Request finished ( FETCH_NODES )   Result: No error
(MEGA) INFO: Users updated ( 1 )
(MEGA) logout
(MEGA) INFO: Request start ( LOGOUT )
(MEGA) 
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffee084700 (LWP 30970)]
0x00007ffff5e51a5d in mega::CommandLogout::procresult (this=0x7fffe8c81a50)
    at src/commands.cpp:1058
1058	        client->sctable->remove();
(gdb) bt
#0  0x00007ffff5e51a5d in mega::CommandLogout::procresult (this=0x7fffe8c81a50)
    at src/commands.cpp:1058
#1  0x00007ffff5e737c4 in mega::Request::procresult (this=0xac7e90, 
    client=0xac78f0) at src/request.cpp:73
#2  0x00007ffff5e11fee in mega::MegaClient::exec (this=0xac78f0)
    at src/megaclient.cpp:725
#3  0x00007ffff5e96004 in mega::MegaApiImpl::loop (this=0xaab9d0)
    at src/megaapi_impl.cpp:2299
#4  0x00007ffff5e938d0 in mega::MegaApiImpl::threadEntryPoint (param=0xaab9d0)
    at src/megaapi_impl.cpp:1784
#5  0x00007ffff7bc4182 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff78f100d in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb)
```

To rule out an issue with the python CLI code, this also fails:
```python
import sys
import os
import time

# Assumes we're in examples/python.
libsdir = os.getcwd() + '/../../bindings/python'
if os.path.isdir(libsdir) and os.path.isfile(libsdir + '/.libs/_mega.so'):
    sys.path.insert(0, libsdir) # mega.py
    sys.path.insert(0, libsdir + '/.libs') # _mega.so

from mega import *

def wait(arg, t=0.5):
    while not arg():
        time.sleep(t)

def main():
    api = MegaApi('APIKEY', None, None)
    api.login('EMAIL', 'PASSWORD')
    wait(api.isLoggedIn)
    api.logout()
    wait(lambda: not api.isLoggedIn())

if __name__ == '__main__':
    main()
```

**Comment by javiserrano** [comment]
Thank you very much for your report.
The bug shoud be fixed now. If you find any other problem please let us know,
